/**
 * @file ff_components.hpp
 * @brief Components management installed on a FF spacecraft
 */

#ifndef S2E_FF_SIMULATION_SPACECRAFT_FF_COMPONENTS_HPP_
#define S2E_FF_SIMULATION_SPACECRAFT_FF_COMPONENTS_HPP_

#include <environment/global/global_environment.hpp>
#include <environment/local/local_environment.hpp>
#include <simulation/spacecraft/installed_components.hpp>

#include "../case/ff_inter_spacecraft_communication.hpp"

// include for components
#include <components/ideal/force_generator.hpp>
#include <components/ideal/torque_generator.hpp>
#include <components/real/cdh/on_board_computer.hpp>

#include "../../components/analyzer/relative_orbit_analyzer.hpp"
#include "../../components/aocs/laser_distance_meter.hpp"
#include "../../components/aocs/qpd_positioning_sensor.hpp"
#include "../../components/aocs/relative_attitude_sensor.hpp"
#include "../../components/aocs/relative_distance_sensor.hpp"
#include "../../components/aocs/relative_position_sensor.hpp"
#include "../../components/aocs/relative_velocity_sensor.hpp"
#include "../../components/controller/relative_orbit_controller_chief.hpp"
#include "../../components/ideal/initialize_relative_attitude_controller.hpp"

class RelativeOrbitControllerChief;

/**
 * @class FfComponents
 * @brief A components class for FF satellite
 */
class FfComponents : public InstalledComponents {
 public:
  /**
   * @fn FfComponents
   * @brief Constructor
   */
  FfComponents(const Dynamics* dynamics, const Structure* structure, const LocalEnvironment* local_env, const GlobalEnvironment* glo_env,
               const SimulationConfiguration* config, ClockGenerator* clock_gen, const RelativeInformation* rel_info,
               FfInterSpacecraftCommunication& inter_spacecraft_communication);
  /**
   * @fn ~FfComponents
   * @brief Destructor
   */
  ~FfComponents();

  // Override functions for InstalledComponents
  /**
   * @fn GenerateForce_b_N
   * @brief Return force generated by components in unit Newton in body fixed frame
   */
  libra::Vector<3> GenerateForce_b_N();
  /**
   * @fn GenerateTorque_b_Nm
   * @brief Return torque generated by components in unit Newton-meter in body fixed frame
   */
  libra::Vector<3> GenerateTorque_b_Nm();
  /**
   * @fn LogSetup
   * @brief Setup the logger for components
   */
  void LogSetup(Logger& logger);

  // Getter
  inline RelativeDistanceSensor& GetRelativeDistanceSensor1() const { return *relative_distance_sensor1_; }
  inline RelativePositionSensor& GetRelativePositionSensor1() const { return *relative_position_sensor1_; }
  inline RelativeVelocitySensor& GetRelativeVelocitySensor1() const { return *relative_velocity_sensor1_; }
  inline RelativeDistanceSensor& GetRelativeDistanceSensor2() const { return *relative_distance_sensor2_; }
  inline RelativePositionSensor& GetRelativePositionSensor2() const { return *relative_position_sensor2_; }
  inline RelativeVelocitySensor& GetRelativeVelocitySensor2() const { return *relative_velocity_sensor2_; }
  inline ForceGenerator& GetForceGenerator() const { return *force_generator_; }

 private:
  // Components
  // CDH
  OnBoardComputer* obc_;  //!< On board computer
  // Sensors
  RelativeDistanceSensor* relative_distance_sensor1_;  //!< Example of Relative distance sensor for deputy 1
  RelativePositionSensor* relative_position_sensor1_;  //!< Example of Relative position sensor for deputy 1
  RelativeAttitudeSensor* relative_attitude_sensor1_;  //!< Example of Relative attitude sensor for deputy 1
  RelativeVelocitySensor* relative_velocity_sensor1_;  //!< Example of Relative velocity sensor for deputy 1
  RelativeDistanceSensor* relative_distance_sensor2_;  //!< Example of Relative distance sensor for deputy 2
  RelativePositionSensor* relative_position_sensor2_;  //!< Example of Relative position sensor for deputy 2
  RelativeAttitudeSensor* relative_attitude_sensor2_;  //!< Example of Relative attitude sensor for deputy 2
  RelativeVelocitySensor* relative_velocity_sensor2_;  //!< Example of Relative velocity sensor for deputy 2

  LaserDistanceMeter* laser_distance_meter_;
  QpdPositioningSensor* qpd_positioning_sensor_;
  // Actuators
  RelativeOrbitControllerChief* relative_orbit_controller_;  // !< Relative orbit controller
  RelativeOrbitAnalyzer* relative_orbit_analyzer_;           // !< Relative orbit analyzer
  ForceGenerator* force_generator_;                          //!< Example of force generator
  TorqueGenerator* torque_generator_;                        //!< Example of torque generator
  // RelativeAttitudeController* relative_attitude_controller_;  //!< Example of attitude controller

  // References
  const Dynamics* dynamics_;               //!< Dynamics information of the spacecraft
  const Structure* structure_;             //!< Structure information of the spacecraft
  const LocalEnvironment* local_env_;      //!< Local environment information around the spacecraft
  const GlobalEnvironment* glo_env_;       //!< Global environment information
  const SimulationConfiguration* config_;  //!< Simulation settings
  const RelativeInformation* rel_info_;    //!< Relative information
  FfInterSpacecraftCommunication& inter_spacecraft_communication_;
};

#endif  // S2E_FF_SIMULATION_SPACECRAFT_FF_COMPONENTS_HPP_
