name: validate / renovate.json

on:
  pull_request:
    paths:
      - 'renovate.json'
      - '.github/workflows/validate-renovate.yml'

jobs:
  validate-renovate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - uses: actions/setup-node@v4

      - name: install
        run: |
          npm install -g renovate
      - name: validate
        run: |
          renovate-config-validator
